# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    

env:
  PATCH_VER: 1.0.1
  
jobs:
  
  patch-build:

    runs-on: ubuntu-latest
    defaults:
     run:
      working-directory: ./my-app
   
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8.0.302+8'
        distribution: 'adopt'
        
    - name: Patch JAR version
      run: mvn versions:set -D newVersion=${{ env.PATCH_VER }}
      
    - name: Compile with Maven
      run: mvn compile
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Create artifact for the build
      uses: actions/upload-artifact@v2
      with:
        name: maven-build
        path: my-app
        
  build-image-and-push:
  

      needs: patch-build
      runs-on: ubuntu-latest
      steps:
        - name: Download build artifact
          uses: actions/download-artifact@v2
          with: 
            name: maven-build
            path: build/
            
        - name: Login to DockerHub
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            
        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1
            
            
        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
           context: ./build
           file: ./build/Dockerfile
           push: true
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/mavenhelloworld:${{ env.PATCH_VER }}
     
  run-image:
       
       name: Run the Docker Image created in previous job
       runs-on: ubuntu-latest
       container:
         image: ${{ secrets.DOCKERHUB_USERNAME }}/mavenhelloworld:${{ env.PATCH_VER }}
         
       steps:
        - name: Run image and log the user
          run: |
            whoami
         

        

            
        
          
      
      
