# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    


jobs:
  
  patch-build:

    runs-on: ubuntu-latest
    env:
      PATCH_VER: 1.0.1
      IMAGE_NAME: maven-hello-world:$PATCH_VER
   
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8.0.302+8'
        distribution: 'adopt'
        
    - name: Patch JAR version
      run: cd my-app && mvn versions:set -D newVersion=${{ env.PATCH_VER }}
      
    - name: Compile with Maven
      run: cd my-app && mvn compile
    
    - name: Build with Maven
      run: cd my-app && mvn -B package --file pom.xml
      
    - name: Create artifact for the build
      uses: actions/upload-artifact@v2
      with:
        name: maven-build
        path: my-app
        
  build-image-and-push:
  

      needs: patch-build
      runs-on: ubuntu-latest
      steps:
        - name: Download build artifact
          uses: actions/download-artifact@v2
          with: 
            name: maven-build
            
        - name: Login to DockerHub
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            
        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1
            
            
        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
           context: /home/runner/work/maven-hello-world/maven-hello-world/my-app
           file: /home/runner/work/maven-hello-world/maven-hello-world/my-app/Dockerfile
           push: true
           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mavenhelloworld:${{ env.PATCH_VER }}
            
        
          
      
      
